export const UPDATE_ACCESS_TOKEN_PAIR = 'UPDATE_ACCESS_TOKEN_PAIR';
export const UPDATE_REQUEST_TOKEN_PAIR = 'UPDATE_REQUEST_TOKEN_PAIR';

export const SET_PROFILE_IMAGE_URL = 'SET_PROFILE_IMAGE_URL';
export const SET_PROFILE_LINK_COLOR = 'SET_PROFILE_LINK_COLOR';
export const UPDATE_WEIGHTED_STATUS = 'UPDATE_WEIGHTED_STATUS';

export const TOGGLE_LAUNCH_ON_START_UP = 'TOGGLE_LAUNCH_ON_START_UP';
export const TOGGLE_COLOR_THEME = 'TOGGLE_COLOR_THEME';

export const ON_LOGOUT = 'ON_LOGOUT';
